### ISSUE TITLE
FR: Change data volume from file based to partition

### ISSUE THREAD

**Issue by nofuturekid** [tds2021/Pi-Zero-W-Smart-USB-Flash-Drive#5]
I think it would make more sense to have the job files on a separate FAT32 partition.

Partition layout could be something like:

1. partition would be "/boot"
2. partition "/" (lets say 2GB?)
3. partition "/mnt/printfiles" (Rest of the SDcard)

That would remove the "need" and time consuming resize of that image file.

**Comment by JobyB** [comment]
I don't think that would work, I believe that the mass storage driver requires a bin file to mount in order to emulate a USB drive.

**Comment by nofuturekid** [comment]
Luckily it don't. The "file" parameter also accepts partitions like so "/dev/mmcblkp3".

**Comment by tds2021** [comment]
I'm not sure how to do that as an IMG file that auto expands and fills the SD cArd.  TI will take some time to figure that one out.  It seems like a good solution, but I don't know when I'll get to it.  I'll keep this open as a reminder to think about it.

**Comment by nofuturekid** [comment]
Sure. If it's the last partition resize should be pretty "easy" because fdisk and alike a clever enough to find out the start for a partition based on the already existing ones. This here could be a starting point: https://unix.stackexchange.com/questions/373063/auto-expand-last-partition-to-use-all-unallocated-space-using-parted-in-batch-m

**Comment by JobyB** [comment]
You could fix the partition size for the os, say 6GB that should give plenty of room then let the last partition be the share and fill it to max, stipulating a 8GB minimum for the SD card I don't think is a big deal.

**Comment by nofuturekid** [comment]
Perhaps this helps too:

Loading the module
*  modprobe g_mass_storage removable=1

Making available via USB OTGt:
* echo "/dev/mmcblk0p3" | sudo tee /sys/devices/platform/soc/20980000.usb/gadget/lun0/file

Remove
* echo "" | sudo tee /sys/devices/platform/soc/20980000.usb/gadget/lun0/file

So it's not necessary to unload/load the kernel module anymore.

**Comment by tds2021** [comment]
I tried to make this change, and had it working when attached to my laptop.  however, when connected to the printer, it causes the printer to hang and will not start a print job.  it seems like the socket interface gets hung up reading from the USB when mounting this way.  I may try and do this in a future release when I have more time to try and test this out, but there are no logs from the printer to know what is going wrong.  It's a lot of trail and error. Instead, I switched the img file creation to dynamically locate the disk space.  This improves the img file expansion because no data is written in the dd command.  much faster, and the same no matter the image size.
